package org.apache.maven.plugin.jdiff;

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import java.util.ResourceBundle;

import org.apache.maven.doxia.sink.Sink;
import org.apache.maven.reporting.MavenReportException;

/**
 * Generator of the JDiff report 
 */
public class JDiffReportGenerator
{
    /**
     * Generate the report.
     * 
     * @param bundle the resource bundle
     * @param sink the sink
     * @throws MavenReportException
     */
    public void doGenerateReport( ResourceBundle bundle, Sink sink )
    throws MavenReportException
    {
        sink.head();
        sink.title();
        sink.text( "JDiff API Difference Report" );
        sink.title_();
        sink.head_();

        sink.body();
        sink.section1();

        sink.sectionTitle1();
        sink.text( "JDiff API Difference Report" );
        sink.sectionTitle1_();

        sink.paragraph();
        sink.text( "The pages generated by JDiff is on a separate page.  It can be found " );
        sink.link( "jdiff/changes.html" );
        sink.text( "here" );
        sink.link_();
        sink.text( "." );
        sink.paragraph_();

        sink.section1_();
        sink.body_();
    }

}
